/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as DashboardCompanyCompanyIdRouteRouteImport } from './routes/dashboard/company.$companyId/route'
import { Route as DashboardCompanyCompanyIdHomeRouteImport } from './routes/dashboard/company.$companyId/home'
import { ServerRoute as ApiV1HealthServerRouteImport } from './routes/api.v1.health'

const rootServerRouteImport = createServerRootRoute()

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCompanyCompanyIdRouteRoute =
  DashboardCompanyCompanyIdRouteRouteImport.update({
    id: '/company/$companyId',
    path: '/company/$companyId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCompanyCompanyIdHomeRoute =
  DashboardCompanyCompanyIdHomeRouteImport.update({
    id: '/home',
    path: '/home',
    getParentRoute: () => DashboardCompanyCompanyIdRouteRoute,
  } as any)
const ApiV1HealthServerRoute = ApiV1HealthServerRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/dashboard/company/$companyId': typeof DashboardCompanyCompanyIdRouteRouteWithChildren
  '/dashboard/company/$companyId/home': typeof DashboardCompanyCompanyIdHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/dashboard/company/$companyId': typeof DashboardCompanyCompanyIdRouteRouteWithChildren
  '/dashboard/company/$companyId/home': typeof DashboardCompanyCompanyIdHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/dashboard/company/$companyId': typeof DashboardCompanyCompanyIdRouteRouteWithChildren
  '/dashboard/company/$companyId/home': typeof DashboardCompanyCompanyIdHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password/$token'
    | '/dashboard/company/$companyId'
    | '/dashboard/company/$companyId/home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password/$token'
    | '/dashboard/company/$companyId'
    | '/dashboard/company/$companyId/home'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password/$token'
    | '/dashboard/company/$companyId'
    | '/dashboard/company/$companyId/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
}
export interface FileServerRoutesByFullPath {
  '/api/v1/health': typeof ApiV1HealthServerRoute
}
export interface FileServerRoutesByTo {
  '/api/v1/health': typeof ApiV1HealthServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/v1/health': typeof ApiV1HealthServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/api/v1/health'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/api/v1/health'
  id: '__root__' | '/api/v1/health'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiV1HealthServerRoute: typeof ApiV1HealthServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/company/$companyId': {
      id: '/dashboard/company/$companyId'
      path: '/company/$companyId'
      fullPath: '/dashboard/company/$companyId'
      preLoaderRoute: typeof DashboardCompanyCompanyIdRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/company/$companyId/home': {
      id: '/dashboard/company/$companyId/home'
      path: '/home'
      fullPath: '/dashboard/company/$companyId/home'
      preLoaderRoute: typeof DashboardCompanyCompanyIdHomeRouteImport
      parentRoute: typeof DashboardCompanyCompanyIdRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface DashboardCompanyCompanyIdRouteRouteChildren {
  DashboardCompanyCompanyIdHomeRoute: typeof DashboardCompanyCompanyIdHomeRoute
}

const DashboardCompanyCompanyIdRouteRouteChildren: DashboardCompanyCompanyIdRouteRouteChildren =
  {
    DashboardCompanyCompanyIdHomeRoute: DashboardCompanyCompanyIdHomeRoute,
  }

const DashboardCompanyCompanyIdRouteRouteWithChildren =
  DashboardCompanyCompanyIdRouteRoute._addFileChildren(
    DashboardCompanyCompanyIdRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardCompanyCompanyIdRouteRoute: typeof DashboardCompanyCompanyIdRouteRouteWithChildren
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardCompanyCompanyIdRouteRoute:
    DashboardCompanyCompanyIdRouteRouteWithChildren,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiV1HealthServerRoute: ApiV1HealthServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
